SE2-Gruppe-E-Royal-Dog/GruppenPhaseAndroid

- .idea/misc.xml
- app/src/main/java/com/uni/gruppenphaseandroid/SensorManagement.java
- app/src/main/java/com/uni/gruppenphaseandroid/SensorReader.java
- core/src/main/java/com/se2/communication/dto/MessageType.java
Fügt eine Klasse hinzu um das Kippen des Handys aus zu lesen
> cheat_KippSensor

- .idea/deploymentTargetDropDown.xml
- app/build.gradle
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/Figure.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/GoalField.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/PlayingField.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/StartingAreaField.java
- app/src/main/res/layout/activity_ingame.xml
- app/src/test/java/com/uni/gruppenphaseandroid/playingfieldtests/FieldTest.java
- app/src/test/java/com/uni/gruppenphaseandroid/playingfieldtests/PlayingFieldTest.java
- app/src/test/java/com/uni/gruppenphaseandroid/playingfieldtests/StartingFieldTest.java
Added unit tests for the classes Field, PlayingField, StartField.
Also imported Mockito for testing.
> issue #16 added unit tests for playingField classes and fixed issues

- app/src/main/java/com/uni/gruppenphaseandroid/SensorReader_Light.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/Color.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/Field.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/FieldUI.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/FieldUIimpl.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/Figure.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/PlayingField.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/Wormhole.java
> #34 wormholes

- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/Field.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/PlayingField.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/Wormhole.java
- app/src/test/java/com/uni/gruppenphaseandroid/playingfieldtests/PlayingFieldTest.java
Fixed bug where the playing field structure got destroyed while switching wormholes randomly. Also fixed test bug with the field UI.
> issue #34 fixed wormhole bug

- .idea/misc.xml
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/Wormhole.java
- app/src/test/java/com/uni/gruppenphaseandroid/playingfieldtests/FieldTest.java
added tests for getNewFieldforWormholeSwitch in class Wormhole and switchField in class Field
> Test switchMethode und Wurmlöcher

- app/src/test/java/com/uni/gruppenphaseandroid/WormholeTest.java
> Wormhole test

- app/src/main/java/com/uni/gruppenphaseandroid/InGameFragment.java
- app/src/main/java/com/uni/gruppenphaseandroid/manager/GameManager.java
> fixed wormholeMessageRecieved

- app/src/main/java/com/uni/gruppenphaseandroid/InGameFragment.java
- app/src/main/java/com/uni/gruppenphaseandroid/MainActivity.java
- app/src/main/java/com/uni/gruppenphaseandroid/manager/GameManager.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/FigureManager.java
- app/src/test/java/com/uni/gruppenphaseandroid/managertests/GamemanagerTest.java
Added unit tests for gamemanager
> added unit tests for gamemanager, also refactored gamemanager slightly

- app/src/main/java/com/uni/gruppenphaseandroid/Cards/Card.java
- app/src/main/java/com/uni/gruppenphaseandroid/manager/GameManager.java
- app/src/main/java/com/uni/gruppenphaseandroid/manager/TurnPhase.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/Figure.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/FigureManager.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/FigureUI.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/FigureUIimpl.java
- app/src/test/java/com/uni/gruppenphaseandroid/checkIfCardIsPlayableTest.java
Implemented the figure onclicklistener. Added base structure for checks when figure is selected. Implemented algorithm that checks if there are any possible moves with the current hand.
> #62 figur auswählen

- app/src/test/java/com/uni/gruppenphaseandroid/manager/LastTurnTest.java
- app/src/test/java/com/uni/gruppenphaseandroid/playingfield/FigureTest.java
Commented out broken unit tests for figures
> commented out broken tests

- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/PlayingField.java
- app/src/test/java/com/uni/gruppenphaseandroid/playingfieldtests/PlayingFieldTest.java
Refactored move method inside playingfield
> refactored move method in playingfield and adjusted tests

- .idea/misc.xml
- app/src/main/java/com/uni/gruppenphaseandroid/manager/GameManager.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/PlayingField.java
- app/src/test/java/com/uni/gruppenphaseandroid/playingfieldtests/PlayingFieldTest.java
> #40 cheat move

- .idea/misc.xml
- app/src/main/java/com/uni/gruppenphaseandroid/cards/Card.java
- app/src/test/java/com/uni/gruppenphaseandroid/PlayCardTest.java
- app/src/test/java/com/uni/gruppenphaseandroid/checkIfCardIsPlayableTest.java
checkEqualCard und playEqualCard hinzugefügt
Tests für checkEqualCards und ein paar Exceptiontests
> Equal card ausspielen

- app/src/main/java/com/uni/gruppenphaseandroid/cards/CardUI.java
- app/src/main/java/com/uni/gruppenphaseandroid/communication/dto/SendCardsPayload.java
- app/src/main/java/com/uni/gruppenphaseandroid/manager/GameManager.java
- app/src/main/java/com/uni/gruppenphaseandroid/manager/Handcards.java
removed test cards because we not get the cards from the server
> fixed type of cards in sendCardsPayload

- .idea/compiler.xml
fixing bug with bytecodetargetlevel
> tried fixing bytecode target level bug

- app/src/main/java/com/uni/gruppenphaseandroid/CardViewFragment.java
- app/src/main/java/com/uni/gruppenphaseandroid/InGameFragment.java
- app/src/main/java/com/uni/gruppenphaseandroid/cards/CardUI.java
- app/src/main/java/com/uni/gruppenphaseandroid/cards/Cardtype.java
- app/src/main/java/com/uni/gruppenphaseandroid/manager/CardManager.java
- app/src/main/java/com/uni/gruppenphaseandroid/manager/GameManager.java
- app/src/main/java/com/uni/gruppenphaseandroid/manager/VisualEffectsManager.java
- app/src/main/java/com/uni/gruppenphaseandroid/manager/VisualEffectsManagerImpl.java
fixed stack image on client and problem of 13 card
> fixed 13 card error 

- app/src/main/java/com/uni/gruppenphaseandroid/cards/Card.java
- app/src/main/java/com/uni/gruppenphaseandroid/manager/CardManager.java
- app/src/main/java/com/uni/gruppenphaseandroid/manager/GameManager.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/Figure.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/FigureUIimpl.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/PlayingField.java
Fixed various bugs for magnet card, switch card and various nullpointer exceptions in checkMoving
> Selected card bugfix

- .idea/compiler.xml
- .idea/misc.xml
- app/build.gradle
- app/src/main/java/com/uni/gruppenphaseandroid/InGameFragment.java
- app/src/main/java/com/uni/gruppenphaseandroid/MainActivity.java
- app/src/main/java/com/uni/gruppenphaseandroid/MenuFragment.java
- app/src/main/java/com/uni/gruppenphaseandroid/service/WebSocketService.java
removed some unused code
excluded fragments and mainActivity from coverage
fixed last remaining bug
> reinterrupt thread

- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/Citizen.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/Figure.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/FigureManager.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/Jerk.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/Knight.java
- app/src/test/java/com/uni/gruppenphaseandroid/playingfieldtests/FigureMovingPossibleTest.java
- app/src/test/java/com/uni/gruppenphaseandroid/playingfieldtests/FigureTest.java
- app/src/test/java/com/uni/gruppenphaseandroid/playingfieldtests/PlayFieldMoveTest.java
Fixed some smells in Figure Klassen
> Code smell fix dagmar

- app/src/main/java/com/uni/gruppenphaseandroid/cards/Card.java
- app/src/main/java/com/uni/gruppenphaseandroid/manager/GameManager.java
- app/src/main/java/com/uni/gruppenphaseandroid/manager/VisualEffectsManagerImpl.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/Figure.java
Fixed various Bugs regarding isMoving and added detection for end of game
> Game manager refactoring

- app/src/main/java/com/uni/gruppenphaseandroid/LeaderboardFragment.java
- app/src/main/java/com/uni/gruppenphaseandroid/playingfield/FigureUIimpl.java
> fixed layout

- app/src/main/java/com/uni/gruppenphaseandroid/InGameFragment.java
- app/src/main/java/com/uni/gruppenphaseandroid/MainActivity.java
- app/src/main/java/com/uni/gruppenphaseandroid/cards/CardAdapter.java
- app/src/main/java/com/uni/gruppenphaseandroid/cards/CardUI.java
- app/src/main/java/com/uni/gruppenphaseandroid/manager/GameManager.java
- app/src/main/java/com/uni/gruppenphaseandroid/manager/VisualEffectsManagerImpl.java
- app/src/test/java/com/uni/gruppenphaseandroid/CardUITest.java
- app/src/test/java/com/uni/gruppenphaseandroid/managertests/GameManagerWormholeTest.java
- app/src/test/java/com/uni/gruppenphaseandroid/managertests/GamemanagerTest.java
cardUI is no longer a singolton and switch cases removed
> CardUI Class update
